#pragma config(Sensor, S1,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int spiral = 1;
	int follow = 2;
	int leave = 0;
	int straight = 3;
	int mode = spiral;
	while(true)
	{

		if(mode == spiral)
		{
			int times = 0;
			int speedleft = 100;
			int speedright = 5;
			while(times < 50)
			{
				motor(left) = speedleft;
				motor(right) = speedright;
				times = times + 1;
				speedleft = speedleft - 1;
				speedright = speedright + 1;
				wait1Msec(500);


			}
		}
		mode = follow;
	if(mode == follow)
	{
		while(leave < 5)
		{
		while(SensorValue(button) == 0)
		{
	  	motor(left) = 50;
	  	motor(right) = 50;
		}
  	while(SensorValue(button) == 1)
 		{
    	motor(left) = -75;
    	motor(right) = -75;
    	wait1Msec(500);
    	motor(left) = 0;
    	motor(right) = -20;
    	wait1Msec(3000);
 		}
  	while(SensorValue(button) == 0)
  	{
  		motor(left) = 40;
  		motor(right) = 100;
  		wait1Msec(100);
		}
	leave = leave + 1;
	}
	}
	mode = straight;
	if(mode == straight)
	{
	  motor(left) = 0;
		motor(right) = -20;
		wait1Msec(4000);
		motor(left) = 100;
		motor(right) = 100;
		wait1Msec(4000);
	}
	}
}
